app/models.py
from app import db
from flask_login import UserMixin
from sqlalchemy import func


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), nullable=False)
    email = db.Column(db.String(200), nullable=False)
    password = db.Column(db.String(300), nullable=False)
    todos = db.relationship('Todo')


class Todo(db.Model):
    __tablename__ = 'todos'

    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(1000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/__init__.py
from flask import Flask
from .config import DevConfig
from flask_bootstrap import Bootstrap5
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "todos.db"


def create_app():
    app = Flask(__name__)
    app.config.from_object(DevConfig)
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    bootstrap = Bootstrap5(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/auth/')

    from .models import User, Todo

    create_db(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_db(app):
    if not path.exists('flask-todo/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database')

app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from .models import User, Todo
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                flash('Login successful', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.index'))
            else:
                flash('Wrong credentials.', category='error')
        else:
            flash('Email does not exist. Try signing up first', category='error')

    return render_template('login.html', user=current_user)


@auth.route('/logout', methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/signup', methods=["GET", "POST"])
def signup():

    if request.method == "POST":
        data = request.form
        username = data.get('username')
        email = data.get('email')
        password = data.get('password')
        password2 = data.get('password2')

        if len(username) < 3:
            flash('Username should be atleast 3 characters', category='error')

        elif len(password) < 8:
            flash("Your password is less than 8 characters", category='error')

        elif password != password2:
            flash('Passwords do not match', category='error')

        else:
            new_user = User(username=username, email=email, password=generate_password_hash(password, method='SHA256'))

            user_exist_check = User.query.filter_by(email=email).first()

            if user_exist_check:
                flash('Email is already in use. Try loggin in', category='error')
            else:
                db.session.add(new_user)
                db.session.commit()
                flash('Account created successfully. You can now login', category='success')
                return redirect(url_for('auth.login'))

    return render_template('signup.html', user=current_user)

app/views.py
from flask import Blueprint, render_template, request, flash, jsonify, json
from flask_login import login_required, current_user
from .models import Todo
from app import db

views = Blueprint('views', __name__)


@views.route('/', methods=["GET", "POST"])
@login_required
def index():

    if request.method == "POST":
        todo = request.form.get('todo')

        if len(todo) < 2:
            flash('Todo should be atlest 2 characters', category='error')
        else:
            new_todo = Todo(task=todo, user_id=current_user.id)

            db.session.add(new_todo)
            db.session.commit()

            flash('Todo added successfuly', category='success')

    return render_template('index.html', user=current_user)


@views.route('/delete-note', methods=["POST"])
@login_required
def delete_note():
    todo = json.loads(request.data)
    todoid = todo['todoId']
    get_todo = Todo.query.get(todoid)
    if get_todo:
        if get_todo.user_id == current_user.id:
            db.session.delete(get_todo)
            db.session.commit()
        return jsonify({})

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% block styles %}
          <!-- Bootstrap CSS -->
          {{ bootstrap.load_css() }}
        {% endblock %}

        <title>ToDo</title>
    {% endblock %}
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container-fluid d-flex justify-content-between">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            <a class="navbar-brand fs-4 fw-bolder">F-ToDO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
              <a href="{{ url_for('views.index') }}" class="nav-link active rounded mx-4" aria-current="page">Home</a>
            </li>
              <li class="nav-item">
              <a href="{{ url_for('auth.logout') }}" class="nav-link active rounded mx-4" aria-current="page">Logout</a>
            </li>
              {% else %}
              <li class="nav-item">
              <a href="{{ url_for('auth.signup') }}" class="nav-link active rounded mx-4" aria-current="page">Signup</a>
            </li>
              <li class="nav-item">
              <a href="{{ url_for('auth.login') }}" class="nav-link active rounded mx-4" aria-current="page">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

  <div class="container">

      <div class="my-2">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
        {% if category == 'error' %}
            <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
                <div class="text-center">
                    {{ message }}
                </div>
                 <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% else %}
            <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
                <div  class="text-center">
                    {{ message }}
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
      {% endif %}
      {% endfor %}
            {% endif %}
          {% endwith %}
      </div>

      {% block content %}

      {% endblock %}
  </div>

  {% block scripts %}
    <!-- Bootstrap JS -->
    {{ bootstrap.load_js() }}

    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
  {% endblock %}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center">
    <form method="POST" class="w-75 mt-4 card p-3">
    <p class="fw-bold">Add a Todo <span class="fw-light fst-italic">as @{{ user.username }}</span></p>
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="todo" placeholder="Add a ToDo" aria-label="a new todo" aria-describedby="button-addon2">
        <button type="submit" class="btn btn-outline-success" id="button-addon2">Add</button>
    </div>
</form>
</div>

<div class="mt-5">
    <ol class="list-group list-group-numbered">
        {% for todo in user.todos %}
        <li class="list-group-item my-2">{{ todo.task }} <span class="float-end" onclick="deleteTodo({{ todo.id }})"><button type="button" class="btn">&times</button></span></li>
        {% endfor %}
    </ol>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="d-flex justify-content-center mt-5">
    <div class="card w-50">
    <p class="card-header fs-3 text-center">Login</p>
    <div class="card-body">
        <form method="POST">
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Enter a valid email" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" id="password" class="form-control"  placeholder="Enter a password atleast 8 characters" required>
            </div>

            <button type="submit" class="btn btn-primary w-100 my-3">Login</button>
        </form>
    </div>
</div>
</div>

{% endblock %}

app/templates/logout.html
{% extends 'base.html' %}

app/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="d-flex justify-content-center mt-5">
    <div class="card w-50">
    <p class="card-header fs-3 text-center">Signup</p>
    <div class="card-body">
        <form method="POST">
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" name="username" id="username" class="form-control" placeholder="Enter a username">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Enter a valid email">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" id="password" class="form-control"  placeholder="Enter a password atleast 8 characters">
            </div>
            <div class="mb-3">
                <label for="password2" class="form-label">Confirm Password</label>
                <input type="password" name="password2" id="password2" class="form-control" placeholder="confirm password">
            </div>

            <button type="submit" class="btn btn-primary w-100 my-3">Sign Up</button>
        </form>
    </div>
</div>
</div>

{% endblock %}